stages:
  - lint
  - build
  - test
  - release

lint:
  stage: lint
  image: golang:latest
  script:
    - go install golang.org/x/lint/golint@latest
    - golint ./...

build:
  stage: build
  image: golang:latest
  script:
    - go build -o myapp

test:
  stage: test
  image: golang:latest
  script:
    - go test

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: 'v0.1.$CI_PIPELINE_IID'                # The version is incremented per pipeline.
    description: 'v0.1.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.
