displayName: Custom Headers
summary: Renames the HTTP response headers.
type: middleware
import: github.com/AdamEszes/traefik-custom-headers-plugin
testData:
  renameData:
    - existingHeaderName: "Customheader"
      newHeaderName: "customheader"

